"""Chat API endpoints for VietCycleConnect AI Assistant."""

import logging
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field

from app.api.dependencies import get_agent_orchestration_service
from app.core.domain.value_objects import AgentResponse, ChatContext, ChatMessage
from app.infra.adapters import AgentOrchestrationService

router = APIRouter(tags=["chat"])
logger = logging.getLogger(__name__)


class ChatRequest(BaseModel):
    """Chat request model."""

    message: str = Field(..., min_length=1, max_length=10000, description="User message")
    conversation_id: UUID | None = Field(None, description="Optional conversation ID")
    messages: list[ChatMessage] = Field(
        default_factory=list, max_length=50, description="Recent conversation history"
    )


class ChatResponseModel(BaseModel):
    """Chat response model."""

    response: str = Field(..., description="AI assistant response")
    agent_name: str = Field(..., description="Name of agent that handled the request")
    conversation_id: UUID | None = Field(None, description="Conversation ID")
    processing_time_ms: int = Field(..., description="Processing time in milliseconds")
    metadata: dict[str, str] = Field(default_factory=dict, description="Additional metadata")


@router.post("/", response_model=ChatResponseModel)
async def send_message(
    request: ChatRequest,
    agent_service: Annotated[AgentOrchestrationService, Depends(get_agent_orchestration_service)],
) -> ChatResponseModel:
    """Send a message to the AI assistant.

    This endpoint handles the complete flow:
    1. Receives user message
    2. Builds conversation context
    3. Routes to appropriate agent
    4. Returns agent response

    Args:
        request: Chat request with message and optional history.
        agent_service: Agent orchestration service.

    Returns:
        ChatResponseModel: AI assistant response.

    Raises:
        HTTPException: If processing fails.
    """
    try:
        logger.info(
            f"Chat request: "
            f"message length={len(request.message)}, "
            f"history length={len(request.messages)}"
        )

        # Build conversation context
        context = ChatContext(
            recent_messages=request.messages,
            detected_topics=[],
        )

        # Route message through agents
        agent_response: AgentResponse = await agent_service.route_message(
            message=request.message, context=context
        )

        logger.info(
            f"Response generated by {agent_response.agent_name} "
            f"in {agent_response.processing_time_ms}ms"
        )

        # Return response
        return ChatResponseModel(
            response=agent_response.content,
            agent_name=agent_response.agent_name,
            conversation_id=request.conversation_id,
            processing_time_ms=agent_response.processing_time_ms,
            metadata=agent_response.metadata,
        )

    except Exception as e:
        logger.error(f"Chat processing failed: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to process message: {str(e)}",
        ) from e


class HealthCheckResponse(BaseModel):
    """Health check response."""

    status: str
    agent_available: bool
    services_available: dict[str, bool]


@router.get("/health", response_model=HealthCheckResponse)
async def chat_health_check(
    agent_service: Annotated[AgentOrchestrationService, Depends(get_agent_orchestration_service)],
) -> HealthCheckResponse:
    """Check chat service health.

    Args:
        agent_service: Agent orchestration service.

    Returns:
        HealthCheckResponse: Health status.
    """
    return HealthCheckResponse(
        status="healthy",
        agent_available=agent_service._graph_app is not None,
        services_available={
            "agent_orchestration": True,
            "llm_service": True,
            "embedding_service": True,
        },
    )
